name: Update DEB-PKG

on:
  workflow_dispatch:

  schedule:
    - cron: '0 12 4,8,12,16,20,24,28 * *'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check update
        run: |
          bash update.sh
          git push

      - name: Update Repo
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git clone https://${{ secrets.PAT }}@github.com/burhancodes/materialgram-deb.git
          mv materialgram.deb materialgram-deb/dists/stable/main/binary-amd64/
          cd materialgram-deb/dists/stable/main/binary-amd64/
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          git add .
          git push main