name: Update DEB-PKG

on:
  workflow_dispatch:

  schedule:
    - cron: '0 12 4,8,12,16,20,24,28 * *'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check update
        run: |
          bash update.sh
          git push