name: Update DEB-PKG Repository

on:
  workflow_run:
    workflows: ["Update DEB-PKG"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout materialgram-deb repo
        uses: actions/checkout@v4
        with:
          repository: burhancodes/materialgram-deb
          token: ${{ secrets.PAT }}
          path: materialgram-deb

      - name: Update materialgram-deb repo
        run: |
          rm -rf materialgram-deb/dists/stable/main/binary-amd64/Packages.gz
          rm -rf materialgram-deb/pool/main/materialgram/*.deb
          VAR=$(curl -s https://raw.githubusercontent.com/burhancodes/materialgram-deb-builder/master/latestversion)
          echo "VAR=$VAR" >> $GITHUB_ENV
          curl -L https://github.com/burhancodes/materialgram-deb-builder/raw/master/materialgram.deb -o materialgram.deb
          mkdir -p materialgram-deb/pool/main/materialgram
          mv materialgram.deb materialgram-deb/pool/main/materialgram/materialgram-${VAR}.amd64.deb
          cd materialgram-deb
          dpkg-scanpackages pool/main /dev/null | gzip -9c > dists/stable/main/binary-amd64/Packages.gz
          cd ..
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Update DEB package to version $VAR"
          git push origin main
