name: Update DEB-PKG Repository

on:
  workflow_run:
    workflows: ["Update DEB-PKG"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update Repo
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git clone https://${{ secrets.PAT }}@github.com/burhancodes/materialgram-deb.git
          VAR=$(curl -s https://raw.githubusercontent.com/burhancodes/materialgram-deb-builder/master/latestversion)
          echo "VAR=$VAR" >> $GITHUB_ENV
          curl -L https://github.com/burhancodes/materialgram-deb-builder/raw/master/materialgram.deb -o materialgram.deb
          mv materialgram.deb materialgram-deb/dists/stable/main/binary-amd64/materialgram-${VAR}.amd64.deb
          cd materialgram-deb/dists/stable/main/binary-amd64/
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          cd ../../../../
          git add .
          git commit -m "Update DEB package to version $VAR"
          git push origin main


           
          
